name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.6
        with:
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SCRIPT: |
            cd /home/ubuntu/Trabalho-do-Brasil
            git pull origin main
            npm install
            npm run build
            echo "${{ secrets.ENV_VARS }}" > .env
            pm2 restart all
          REMOTE_PORT: 22
          TARGET: /home/${{ secrets.REMOTE_USER }}
          ARGS: -rltgoDzvO
          EXCLUDE: ".git*,node_modules,.env*"
