name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.6
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/trabalho-do-brasil  # Ajuste o diretório conforme necessário
            git pull origin main
            npm install
            npm run build
            echo "${{ secrets.ENV_VARS }}" > .env
            pm2 restart all
