name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.6
        with:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."  
          TARGET: "/home/ubuntu/Trabalho-do-Brasil"  
          ARGS: "-rltgoDzvO"  
          EXCLUDE: ".git*,node_modules, .env*" 
            git pull origin main
            npm install
            npm run build
            echo "${{ secrets.ENV_VARS }}" > .env
            pm2 restart all
